/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-primary-fixed-variant": "#74009f",
        "on-error-container": "#93000a",
        "primary": "#9700cd",
        "surface-container-high": "#e6e8ea",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#001a42",
        "primary-fixed": "#f8d8ff",
        "on-surface": "#191c1e",
        "primary-fixed-dim": "#ecb2ff",
        "error": "#ba1a1a",
        "surface-variant": "#e0e3e5",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f7f9fb",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "secondary-container": "#dae2fd",
        "on-primary-container": "#ffffff",
        "inverse-primary": "#ecb2ff",
        "inverse-on-surface": "#eff1f3",
        "inverse-surface": "#2d3133",
        "on-secondary-container": "#5c647a",
        "on-surface-variant": "#514255",
        "surface-container": "#eceef0",
        "surface": "#f7f9fb",
        "surface-tint": "#9900cf",
        "on-tertiary-container": "#ffffff",
        "secondary-fixed": "#dae2fd",
        "tertiary-fixed": "#d8e2ff",
        "tertiary-fixed-dim": "#adc6ff",
        "secondary": "#565e74",
        "surface-container-low": "#f2f4f6",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#320047",
        "tertiary": "#0059c0",
        "outline-variant": "#d4c0d7",
        "outline": "#837186",
        "tertiary-container": "#2372e5",
        "surface-dim": "#d8dadc",
        "primary-container": "#bd00ff",
        "secondary-fixed-dim": "#bec6e0",
        "surface-container-highest": "#e0e3e5",
        "on-secondary-fixed-variant": "#3f465c",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#004395",
        "background": "#f7f9fb",
        "on-background": "#191c1e",
        "on-secondary-fixed": "#131b2e"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "sm": "16px",
        "margin-mobile": "16px",
        "md": "24px",
        "lg": "48px",
        "xl": "80px",
        "base": "4px",
        "xs": "8px",
        "margin-desktop": "40px",
        "gutter": "24px",
        "container-max": "1280px"
      },
      "fontFamily": {
        "display-lg": ["Geist", "Sora", "sans-serif"],
        "display-lg-mobile": ["Geist", "Sora", "sans-serif"],
        "headline-lg": ["Geist", "Sora", "sans-serif"],
        "headline-md": ["Geist", "Sora", "sans-serif"],
        "body-lg": ["Geist", "Inter", "sans-serif"],
        "body-md": ["Geist", "Inter", "sans-serif"],
        "label-sm": ["JetBrains Mono"],
        "label-mono": ["JetBrains Mono"],
        "button": ["Geist", "Sora", "sans-serif"]
      },
      "fontSize": {
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "display-lg-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "label-mono": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "button": ["14px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
